DROP DATABASE IF EXISTS theLab_db;
CREATE DATABASE theLab_db;

USE theLab_db;

CREATE TABLE user(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    password VARCHAR(25) NOT NULL,
    email VARCHAR(50) NOT NULL
);

CREATE TABLE ideas(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL, 
    user_email VARCHAR(50),
    name VARCHAR(20) NOT NULL,
    idea VARCHAR (500)
);