DROP DATABASE IF EXISTS theLab_db;
CREATE DATABASE theLab_db;
USE theLab_db;

CREATE TABLE User (
    ID int () NOT NULL AUTO_INCREMENT,
    PASSWORD VARCHAR (25) NOT NULL,
    EMAIL VARCHAR (50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Ideas (
    ID int () NOT NULL AUTO_INCREMENT,
    User_ID integer NOT NULL, 
    User_EMAIL VARCHAR (50),
    NAME VARCHAR (20) NOT NULL,
    Idea VARCHAR (500), 
    PRIMARY KEY (id),
    FOEIGN KEY (User_ID) REFERENCES User(ID) 

)